# Generated by Django 6.0.1 on 2026-03-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicitem',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
