# Generated by Django 6.0.1 on 2026-03-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicitem_spotify_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='films/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.section')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('spotify_uri', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('fans', models.CharField(default='2.9k', max_length=20)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.film')),
            ],
        ),
        migrations.DeleteModel(
            name='MusicItem',
        ),
    ]
